include_guard(GLOBAL)

include(FetchContent)

set(FETCHCONTENT_UPDATES_DISCONNECTED ON CACHE BOOL "" FORCE)

if(POLICY CMP0169)
    cmake_policy(SET CMP0169 OLD)
endif()

FetchContent_Declare(
    stdexec_src
    GIT_REPOSITORY https://github.com/NVIDIA/stdexec.git
    GIT_TAG gtc-2026
    GIT_SHALLOW TRUE
    UPDATE_DISCONNECTED TRUE
)

FetchContent_GetProperties(stdexec_src)
if(NOT stdexec_src_POPULATED)
    FetchContent_Populate(stdexec_src)
endif()

set(FLUX_STDEXEC_GENERATED_DIR "${CMAKE_BINARY_DIR}/_deps/flux_stdexec")
file(MAKE_DIRECTORY "${FLUX_STDEXEC_GENERATED_DIR}/include/exec/asio")
file(WRITE "${FLUX_STDEXEC_GENERATED_DIR}/include/exec/asio/asio_config.hpp" [=[
/*
 * Generated by flux's CMake integration.
 */
#pragma once

#define STDEXEC_ASIO_USES_STANDALONE 1
#define STDEXEC_ASIO_USES_BOOST 0

#include <system_error>
#include <asio.hpp>

#define ASIOEXEC_ASIO_NAMESPACE asio

namespace experimental::execution::asio {
  namespace asio_impl = ::asio;
  using error_code = std::error_code;
  using error_condition = std::error_condition;
  using errc = std::errc;
  using system_error = std::system_error;
} // namespace experimental::execution::asio

namespace exec = experimental::execution;
]=])

if(NOT TARGET flux_stdexec_headers)
    add_library(flux_stdexec_headers INTERFACE)
    target_include_directories(flux_stdexec_headers
        SYSTEM
        INTERFACE
            "${stdexec_src_SOURCE_DIR}/include"
            "${FLUX_STDEXEC_GENERATED_DIR}/include")
    target_compile_definitions(flux_stdexec_headers
        INTERFACE
            STDEXEC_ASIO_USES_BOOST=0
            STDEXEC_ASIO_USES_STANDALONE=1)
endif()

find_package(Threads REQUIRED)

if(NOT TARGET flux_asio_headers)
    FetchContent_Declare(
        standalone_asio
        GIT_REPOSITORY https://github.com/chriskohlhoff/asio.git
        GIT_TAG asio-1-30-2
        GIT_SHALLOW TRUE
        UPDATE_DISCONNECTED TRUE
    )

    FetchContent_GetProperties(standalone_asio)
    if(NOT standalone_asio_POPULATED)
        FetchContent_Populate(standalone_asio)
    endif()

    add_library(flux_asio_headers INTERFACE)
    target_include_directories(flux_asio_headers
        SYSTEM
        INTERFACE
            "${standalone_asio_SOURCE_DIR}/asio/include")
    target_compile_definitions(flux_asio_headers
        INTERFACE
            ASIO_STANDALONE=1)
endif()

if(NOT TARGET Boost::headers)
    find_package(Boost QUIET)
endif()

if(NOT TARGET Boost::headers)
    if(Boost_FOUND AND Boost_INCLUDE_DIRS)
        add_library(flux_boost_headers_core INTERFACE)
        target_include_directories(flux_boost_headers_core INTERFACE ${Boost_INCLUDE_DIRS})
        target_compile_definitions(
            flux_boost_headers_core INTERFACE BOOST_ERROR_CODE_HEADER_ONLY=1)
        add_library(Boost::headers ALIAS flux_boost_headers_core)
    else()
        FetchContent_Declare(
            flux_boost_headers_core_src
            URL https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.gz
            DOWNLOAD_EXTRACT_TIMESTAMP FALSE
        )
        FetchContent_MakeAvailable(flux_boost_headers_core_src)

        add_library(flux_boost_headers_core INTERFACE)
        target_include_directories(
            flux_boost_headers_core INTERFACE ${flux_boost_headers_core_src_SOURCE_DIR})
        target_compile_definitions(
            flux_boost_headers_core INTERFACE BOOST_ERROR_CODE_HEADER_ONLY=1)
        add_library(Boost::headers ALIAS flux_boost_headers_core)
    endif()
endif()

if(FLUX_USE_MIMALLOC)
    if(NOT TARGET mimalloc-static AND NOT TARGET mimalloc)
        message(STATUS "Fetching mimalloc")
        set(MI_BUILD_SHARED OFF CACHE BOOL "" FORCE)
        set(MI_BUILD_STATIC ON CACHE BOOL "" FORCE)
        set(MI_BUILD_OBJECT OFF CACHE BOOL "" FORCE)
        set(MI_BUILD_TESTS OFF CACHE BOOL "" FORCE)
        set(MI_BUILD_BENCH OFF CACHE BOOL "" FORCE)
        set(MI_INSTALL_TOPLEVEL OFF CACHE BOOL "" FORCE)
        set(MI_OVERRIDE ON CACHE BOOL "" FORCE)

        FetchContent_Declare(
            mimalloc
            GIT_REPOSITORY https://github.com/microsoft/mimalloc.git
            GIT_TAG v3.1.5
            GIT_SHALLOW TRUE
            UPDATE_DISCONNECTED TRUE
        )

        FetchContent_MakeAvailable(mimalloc)
    endif()
endif()
